### PR TITLE
Refactor test

### PR DESCRIPTION
**Pull request by javierggt**
- Refactor code to move tests into a submodule.
- Pep8/flake8

### CODE REVIEW

**Comment by javierggt** [comment]
This PR is only two commits. It is easier to see the changes separately, because the second one is pep8/flake8.

**Comment by javierggt** [comment]
NOTE: I don't mind merging before/after the scm_version PR. They are conflicting, but they are simple changes, so I can do it either way.

**Comment by taldcroft** [comment]
This was not passing tests locally because `_norm` was not included in the top-level `from quatutil import *`.  So I just made that function public by changing `_norm()` to `norm()` .

Also, the `setup.py` was not resulting in a working (installable) distribution.  I believe one needs to either call `find_packages()` or explicitly provide them in `packages`.  What is confusing to me is that I looked at the source distribution tarball generated with 0d3912c and with my version dc0317a, and by eye I could not see an obvious difference.  But only the latter will import after `pip install .` into a test env.

What we really should be doing is just deprecating this package completely and moving remaining bits of functionality into `chandra_aca.transform`.  I'm opening an issue FWIW.

**Comment by taldcroft** [comment]
About removing this package, I just checked and it does get used in a lot of places.  Probably not worth the effort, though we could port all functionality to `chandra_aca.transform` and recommend that for new code.

**Comment by taldcroft** [comment]
I have reviewed this and tested and it all looks good to me now, so merging.

**Pull request merged**
